"""Add ASX-specific tables

Revision ID: c443b1b0696e
Revises: 
Create Date: 2025-07-06 00:25:08.437614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c443b1b0696e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asx_sectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asx_sectors_id'), 'asx_sectors', ['id'], unique=False)
    op.create_index(op.f('ix_asx_sectors_name'), 'asx_sectors', ['name'], unique=True)
    op.create_table('asx_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('imputation_rate', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['asx_sectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asx_stocks_id'), 'asx_stocks', ['id'], unique=False)
    op.create_index(op.f('ix_asx_stocks_symbol'), 'asx_stocks', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asx_stocks_symbol'), table_name='asx_stocks')
    op.drop_index(op.f('ix_asx_stocks_id'), table_name='asx_stocks')
    op.drop_table('asx_stocks')
    op.drop_index(op.f('ix_asx_sectors_name'), table_name='asx_sectors')
    op.drop_index(op.f('ix_asx_sectors_id'), table_name='asx_sectors')
    op.drop_table('asx_sectors')
    # ### end Alembic commands ###
